### PR TITLE
 .coafile: Add section for XML files

### PR DESCRIPTION
**Pull request by Lucifer24**
Added section for XML files, also
fixed issues raised by XMLBear.

Closes https://github.com/coala/coala-eclipse/issues/39

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Why are files other than `.coafile` are changed?

**Comment by prashant0598** [comment]
@aashutoshrathi i thk he has also used spaceconsistency bear :smile:

**Comment by prashant0598** [comment]
ack 7676c2f

**Comment by Lucifer24** [comment]
@aashutoshrathi @prashant0598 i just ran XMLBear on my machine and it made the changes which was required for it to run.

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
